[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"

[workspace.lints.rust]
unsafe_code = "deny"
unused_must_use = "deny"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
panic_in_result_fn = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "warn"
print_stdout = "deny"
print_stderr = "deny"
dbg_macro = "deny"
let_underscore_must_use = "deny"

[profile.release]
lto = "fat"
codegen-units = 1
debug = 1

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
shahrah-hash = { path = "crates/hash", version = "0.1.0" }
shahrah-protocol = { path = "crates/protocol", version = "0.1.0" }
shahrah-sql = { path = "crates/sql", version = "0.1.0" }
shahrah-topology = { path = "crates/topology", version = "0.1.0" }
shahrah-routing = { path = "crates/routing", version = "0.1.0" }

arc-swap = { version = "1" }
base64 = { version = "0.22" }
bytes = { version = "1" }
hmac = { version = "0.12" }
pbkdf2 = { version = "0.12", default-features = false, features = ["hmac"] }
sha2 = { version = "0.10" }
subtle = { version = "2" }
thiserror = { version = "2.0.20" }
openraft = { version = "0.9", features = ["serde", "storage-v2"] }
serde_json = { version = "1" }
pg_query = { version = "6" }
toml = { version = "0.9" }
rand = { version = "0.9" }
tokio = { version = "1" }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "tls12"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustls-pemfile = { version = "2" }
rustls-native-certs = { version = "0.8" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
xxhash-rust = { version = "0.8.18", features = ["xxh3", "const_xxh3"] }
serde = { version = "1.0.229", default-features = false, features = ["derive"] }