[package]
name = "shahrah-topology"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
openraft = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "fs", "io-util", "net", "macros", "time"] }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }

[lints]
workspace = true
